### ISSUE TITLE
Update Setup Scripts Videos To Cover Declarative Schema

### ISSUE THREAD

**Issue by sprankhub** [mage2tv/topics#173]
Magento 2.3 adds Declarative Schema. I think the setup scripts videos should be updated accordingly or new videos covering the Declarative Schema should be added.

**Comment by Vinai** [comment]
The first batch of videos on declarative schema are already online!
More scripts are written and are waiting to be recorded.

**Comment by sprankhub** [comment]
Ahh I looked for them under "Setup Scripts" and not under "Fundamentals". And i was too dumb to use the search :) Sorry!

**Comment by Vinai** [comment]
Yeah, I wasn’t sure where would make more sense. Just recorded new content for declarative schema data patches FYI :)
